channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - uvicorn=0.24.0.post1
  - fastapi=0.109.1
  - python-multipart=0.0.7
  - email-validator=2.1.0.post1
  - passlib=1.7.4
  - tenacity=8.2.3
  - pydantic>2.0
  - emails=0.6
  
  - jinja2=3.1.2
  - alembic=1.12.1
  - python-jose=3.3.0
  - httpx=0.25.1
  - psycopg=3.1.13
  
  - bcrypt=4.0.1
  - pydantic-settings=2.2.1
  - sentry-sdk=1.40.6
  - pytest=7.4.3  # dev
  - mypy=1.8.0  # dev
  - ruff=0.2.2  # dev
  - pre-commit=3.6.2  # dev

  - coverage=7.4.3  # dev
  - pip
  - pip:
    - uvicorn[standard]
    - passlib[bcrypt]
    - python-jose[cryptography]
    - psycopg[binary]
    - sentry-sdk[fastapi]
    - gunicorn==21.2.0
    - sqlmodel==0.0.16
    - types-python-jose==3.3.4.20240106  # dev
    - types-passlib==1.7.7.20240106  # dev
    - black #dev
